apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: logstash
  name: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: logstash
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: logstash
    spec:
      containers:
      - image: logstash
        imagePullPolicy: ""
        name: logstash
        ports:
        - containerPort: 5140
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
